# docker-compose.yml
version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: covid_alert_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES: postgres

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#  gradle:
#    image: felixpotie/covid_alert:0.0.1-SNAPSHOT
#    ports:
#      - 8085:8085
#    depends_on:
#      - postgres
#    environment:
#      dburl: postgres:5432/postgres

  keycloak:
    image: jboss/keycloak:11.0.2
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_SCHEMA: public
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin

    ports:
    - 8080:8080