# docker-compose.yml
version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: covid_alert
    ports:
    - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES: postgres
  gradle:
    image: jar_app
    ports:
    - '8080:8080'
    environment:
      dburl: postgres:5432/covid_alert