name: covid_alert

on: push

jobs:
  ci:
    runs-on : ubuntu-latest
    container: openjdk:11-jdk
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES: postgres
    steps:
      - uses: actions/checkout@v2
      - run : ./gradlew assemble
      - run : ./gradlew dockerBuildImage
  ci_docker:
    runs-on : ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run : ./gradlew dockerBuildImage
      - run : docker push felixpotie/covid_alert:0.0.1-SNAPSHOT